# Generated by Django 3.2 on 2021-05-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210523_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='owner',
        ),
    ]
