# Generated by Django 3.2 on 2021-05-04 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In progress'), ('IR', 'In review'), ('NW', 'New'), ('RJ', 'Rejected'), ('TD', 'To do')], default='NW', max_length=2, verbose_name='State')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(default='', max_length=2000, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.taskbase')),
                ('type', models.CharField(choices=[('B', 'Bug'), ('I', 'Improvement'), ('T', 'Task')], default='T', max_length=1, verbose_name='Type')),
            ],
            bases=('tasks.taskbase',),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('taskbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.taskbase')),
                ('type', models.CharField(choices=[('B', 'Bug'), ('I', 'Improvement'), ('S', 'Sub-task')], default='S', max_length=1, verbose_name='Type')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            bases=('tasks.taskbase',),
        ),
    ]
