# Generated by Django 3.2 on 2021-05-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskbase_ptr',
        ),
        migrations.RemoveField(
            model_name='taskbase',
            name='creator',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskBase',
        ),
    ]
