# Generated by Django 3.2 on 2021-05-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210524_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Name'),
        ),
    ]
