# Generated by Django 3.2 on 2021-05-24 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('tasks', '0008_auto_20210524_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='project',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
