# Generated by Django 3.2 on 2021-06-02 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0009_subtask_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='asignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='asignee',
        ),
        migrations.AddField(
            model_name='subtask',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_subtask_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_task_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
