# Generated by Django 3.2 on 2021-06-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210603_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('IP', 'In progress'), ('IR', 'In review'), ('NW', 'New'), ('RJ', 'Rejected'), ('TD', 'To do')], default='NW', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DN', 'Done'), ('IP', 'In progress'), ('IR', 'In review'), ('NW', 'New'), ('RJ', 'Rejected'), ('TD', 'To do')], default='NW', max_length=2, verbose_name='State'),
        ),
    ]
