# Generated by Django 3.2 on 2021-07-09 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210609_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, "Title's too short")], verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, "Title's too short")], verbose_name='Title'),
        ),
    ]
