# Generated by Django 3.2.5 on 2021-07-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210713_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Description'),
        ),
    ]
